### ISSUE TITLE
Maybe not is correct drop nans in self.history_x

### ISSUE THREAD

**Issue by Gilianp** [Ekeany/Boruta-Shap#31]
In line 446 (`self.history_x.dropna(axis=0,inplace=True)`) this statement drop all rows that contains nans from history, but some features (those still not removed), have it values dropped also, losing part of its history. So, at the end, the plot remains the same appearance all the times even increasing the `n_trials` parameter, and the means are not computed correctly (with all computed values).

I don't know if you could understand me

**Comment by ploriaux** [comment]
@Gilianp I agree, this is a bug. When you `dropna` from `self.history_x` you end up removing all trials for which features have already been excluded (basically all trials after the first several, or whenever you start to see significance in the binomial H0 test). I have a fix for this and a few other things, @Ekeany can I be added as a collaborator or how do you recommend I create a branch/create a PR?  Otherwise great package. Thanks, -Paul

**Comment by Ekeany** [comment]
Hi Paul,

You can certainly collaborate,  I think the best way is if you fork the
repo and then you can make your changes and then make a pull request back
to master.

Thanks for the help,
Eoghan.

**Comment by ploriaux** [comment]
Thanks @Ekeany created a [PR](https://github.com/Ekeany/Boruta-Shap/pull/47)!

**Comment by Ekeany** [comment]
ploriaux's PR fixed the issue
